version: '3.8'

services:
  flask:
    restart: always
    ports:
      - 5001:80
    image: dmelchor/assemblyai-hackathon-flask
    command: ./start.sh
    env_file:
      - .env
    depends_on:
      - redis
      - db
  celery:
    restart: always
    command: celery -A tasks.celery worker --loglevel=info
    image: dmelchor/assemblyai-hackathon-celery
    env_file:
      - .env
    depends_on:
      - redis
      - db
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./initial.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=assembly_ai
  react:
    restart: always
    image: dmelchor/assemblyai-hackathon-react
    ports:
      - 3000:80
    command: nginx -g 'daemon off;'
    env_file:
      - .env
    depends_on:
      - flask